### ISSUE TITLE
openvswitch: Build Failure, Snapshot

### ISSUE THREAD

**Issue by arrmo** [openwrt/packages#10351]
Maintainer: @yousong 
Environment: ramips_mt76x8_DEVICE_tplink_tl-wr802n-v4, snapshot

Description:
Trying to build the latest snapshot - for the device noted above. I used the snapshot feeds config, and also the config.buildinfo as a starting point. But, when I try to make defconfig (or menuconfig), I get the following,

```
WARNING: Makefile 'package/feeds/telephony/asterisk-16.x/Makefile' has a dependency on 'liblua5.3', which does not exist
WARNING: Makefile 'package/feeds/packages/elektra/Makefile' has a dependency on 'lua5.3', which does not exist
WARNING: Makefile 'package/feeds/packages/luasocket/Makefile' has a dependency on 'liblua5.3', which does not exist
WARNING: Makefile 'package/feeds/packages/openvswitch/Makefile' has a dependency on 'kmod-nsh', which does not exist
```

And then, when I try to build (even though openvswitch is not desired / selected,
```
PYTHONPATH=./python":"$PYTHONPATH PYTHONDONTWRITEBYTECODE=yes /mnt/ProgSSD/openwrt/staging_dir/hostpkg/bin/python3.8 ./ovsdb/ovsdb-idlc.in c-idl-source lib/vswitch-idl.ovsidl > lib/vswitch-idl.c.tmp && mv lib/vswitch-idl.c.tmp lib/vswitch-idl.c
Traceback (most recent call last):
  File "./ovsdb/ovsdb-idlc.in", line 1581, in <module>
    func(*args[1:])
  File "./ovsdb/ovsdb-idlc.in", line 442, in printCIDLSource
    replace_cplusplus_keyword(schema)
  File "./ovsdb/ovsdb-idlc.in", line 179, in replace_cplusplus_keyword
    for columnName in table.columns:
RuntimeError: dictionary keys changed during iteration
make[4]: *** [Makefile:6509: lib/vswitch-idl.c] Error 1
```

And suggestions would be greatly appreciated. Thanks!

**Comment by yousong** [comment]
The RuntimeError should now be fixed by change from @BKPepe 

Reopen the issue since the `kmod-nsh` not found is unexpected.  Can you confirm that you have `nsh` in `package/kernel/linux/modules/netsupport.mk` ?
