### ISSUE TITLE
isc-dhcp: seeing crashes when attempting to update dynamic dns

### ISSUE THREAD

**Issue by pprindeville** [openwrt/packages#14195]
Maintainer: @pprindeville
Environment: x86_64, generic, HEAD (b0cb305236)
Description:

When updating dynamic DNS through DHCP integration, we're seeing the following crash:

```
(gdb) info stack
#0  0x00007f66d350aa4b in catgets (catd=0xffffffffffffffff, set_id=2, 
    msg_id=1, s=0x5bd0cc "success") at src/locale/catgets.c:19
#1  0x0000000000593aa9 in isc_result_tomany_helper.isra ()
#2  0x000000000056a6b5 in req_response ()
#3  0x0000000000599c64 in isc.taskmgr_dispatch ()
#4  0x000000000059c78e in evloop ()
#5  0x000000000059cb1c in isc.app_ctxrun ()
#6  0x00000000004451eb in dispatch ()
#7  0x000000000040529a in main ()
(gdb) 
```

Building with `DISABLE_NLS:=1` doesn't seem to give any relief.

**Comment by pprindeville** [comment]
Tracking upstream as https://gitlab.isc.org/isc-projects/dhcp/-/issues/156.

**Comment by pprindeville** [comment]
There was a PR that is a temporary workaround to this, but a better fix is needed.

Leaving open for now.
