### ISSUE TITLE
latest changes to mainline (toolchain=>gdb+expat) = failed build glib2

### ISSUE THREAD

**Issue by build000** [openwrt/packages#1557]
make[3]: Entering directory '/magazyn/Pliki/openwrt/trunk/feeds/packages/libs/glib2'
make   -C /magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4  
make[4]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4'
make  all-recursive
make[5]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4'
Making all in .
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4'
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4'
Making all in m4macros
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/m4macros'
make  all-am
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/m4macros'
make[7]: Nothing to be done for 'all-am'.
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/m4macros'
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/m4macros'
Making all in glib
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib'
make  all-recursive
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib'
Making all in libcharset
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/libcharset'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/libcharset'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/libcharset'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/libcharset'
Making all in pcre
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/pcre'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/pcre'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/pcre'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/pcre'
Making all in update-pcre
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/update-pcre'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/update-pcre'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/update-pcre'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/update-pcre'
Making all in .
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib'
make[8]: Nothing to be done for 'all-am'.
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib'
Making all in tests
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/tests'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/tests'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/tests'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib/tests'
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib'
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/glib'
Making all in gmodule
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gmodule'
make  all-am
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gmodule'
make[7]: Nothing to be done for 'all-am'.
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gmodule'
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gmodule'
Making all in gthread
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gthread'
make  all-am
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gthread'
make[7]: Nothing to be done for 'all-am'.
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gthread'
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gthread'
Making all in gobject
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject'
make  all-recursive
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject'
Making all in .
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject'
make[8]: Nothing to be done for 'all-am'.
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject'
Making all in tests
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject/tests'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject/tests'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject/tests'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject/tests'
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject'
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gobject'
Making all in gio
make[6]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio'
make  all-recursive
make[7]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio'
Making all in gdbus-2.0/codegen
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/gdbus-2.0/codegen'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/gdbus-2.0/codegen'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/gdbus-2.0/codegen'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/gdbus-2.0/codegen'
Making all in xdgmime
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/xdgmime'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/xdgmime'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/xdgmime'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/xdgmime'
Making all in inotify
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/inotify'
make  all-am
make[9]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/inotify'
make[9]: Nothing to be done for 'all-am'.
make[9]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/inotify'
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/inotify'
Making all in .
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio'
make[8]: Nothing to be done for 'all-am'.
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio'
Making all in tests
make[8]: Entering directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/tests'
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
  GEN      gdbus-test-codegen-generated.h
Traceback (most recent call last):
  File "../../gio/gdbus-2.0/codegen/gdbus-codegen", line 37, in <module>
    from codegen import codegen_main
  File "/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/gdbus-2.0/codegen/codegen_main.py", line 28, in <module>
    from . import parser
  File "/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/gdbus-2.0/codegen/parser.py", line 23, in <module>
    import xml.parsers.expat
  File "/magazyn/Pliki/openwrt/trunk/staging_dir/host/lib/python2.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: No module named pyexpat
Makefile:4511: recipe for target 'gdbus-test-codegen-generated.h' failed
make[8]: *** [gdbus-test-codegen-generated.h] Error 1
make[8]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio/tests'
Makefile:3964: recipe for target 'all-recursive' failed
make[7]: *** [all-recursive] Error 1
make[7]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio'
Makefile:1771: recipe for target 'all' failed
make[6]: *** [all] Error 2
make[6]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/gio'
Makefile:1204: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4'
Makefile:846: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4'
Makefile:105: recipe for target '/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/.built' failed
make[3]: *** [/magazyn/Pliki/openwrt/trunk/build_dir/host/glib-2.43.4/.built] Error 2
make[3]: Leaving directory '/magazyn/Pliki/openwrt/trunk/feeds/packages/libs/glib2'
package/Makefile:191: recipe for target 'package/feeds/packages/glib2/host/compile' failed
make[2]: *** [package/feeds/packages/glib2/host/compile] Error 2
make[2]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
package/Makefile:188: recipe for target '/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.10/stamp/.package_compile' failed
make[1]: *** [/magazyn/Pliki/openwrt/trunk/staging_dir/target-mips_34kc_musl-1.1.10/stamp/.package_compile] Error 2
make[1]: Leaving directory '/magazyn/Pliki/openwrt/trunk'
/magazyn/Pliki/openwrt/trunk/include/toplevel.mk:181: polecenia dla obiektu 'world' nie powiodły się
make: *** [world] Błąd 2

missing pyexpat ?

**Comment by build000** [comment]
https://github.com/openwrt/packages/commit/94f87dc1e1bd076b443e86aa7ba2ccc9c4182cb8 - fix problem
