### ISSUE TITLE
seafile-seahub: fails to compile on arm_cortex-a15_neon-vfpv4

### ISSUE THREAD

**Issue by PolynomialDivision** [openwrt/packages#17212]
Maintainer: @commodo
Description:

```

Applying ./patches/020-Makefile-fixes.patch using plaintext: 
patching file Makefile

Applying ./patches/030-uci-conf.patch using plaintext: 
patching file seahub/settings.py

Applying ./patches/040-manage-shebang.patch using plaintext: 
patching file manage.py
Collecting Django==1.11.29
  Using cached Django-1.11.29.tar.gz (8.0 MB)
Collecting pytz==2021.3
  Using cached pytz-2021.3.tar.gz (320 kB)
Skipping wheel build for Django, due to binaries being disabled for it.
Skipping wheel build for pytz, due to binaries being disabled for it.
Installing collected packages: pytz, Django
    Running setup.py install for pytz: started
    Running setup.py install for pytz: finished with status 'done'
    Running setup.py install for Django: started
    Running setup.py install for Django: finished with status 'done'
Successfully installed Django-1.11.29 pytz-2021.3
make[4]: Entering directory '/builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/seahub-7.1.5-server'
--> Compile locales
/builder/shared-workdir/build/sdk/staging_dir/hostpkg/bin/django-admin compilemessages
Traceback (most recent call last):
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/bin/django-admin", line 33, in <module>
    sys.exit(load_entry_point('Django==1.11.29', 'console_scripts', 'django-admin')())
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/bin/django-admin", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/core/management/__init__.py", line 13, in <module>
    from django.core.management.base import (
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/core/management/base.py", line 17, in <module>
    from django.db.migrations.exceptions import MigrationSchemaMissing
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/db/migrations/__init__.py", line 2, in <module>
    from .operations import *  # NOQA
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/db/migrations/operations/__init__.py", line 1, in <module>
    from .fields import AddField, AlterField, RemoveField, RenameField
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 4, in <module>
    from django.db.models.fields import NOT_PROVIDED
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/db/models/__init__.py", line 5, in <module>
    from django.db.models.deletion import (
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/db/models/deletion.py", line 5, in <module>
    from django.db.models import signals, sql
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/db/models/sql/__init__.py", line 2, in <module>
    from django.db.models.sql.query import *  # NOQA
  File "/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/site-packages/django/db/models/sql/query.py", line 11, in <module>
    from collections import Counter, Iterator, Mapping, OrderedDict
ImportError: cannot import name 'Iterator' from 'collections' (/builder/shared-workdir/build/sdk/staging_dir/hostpkg/lib/python3.10/collections/__init__.py)
make[4]: *** [Makefile:15: locale] Error 1
make[4]: Leaving directory '/builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/seahub-7.1.5-server'
make[3]: *** [Makefile:99: /builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/seahub-7.1.5-server/.built] Error 2
time: package/feeds/packages/seafile-seahub/compile#18.52#5.13#25.70

```

**Comment by commodo** [comment]
Yes, see here https://github.com/openwrt/packages/pull/17206

These will be marked as BROKEN for a while.
