### ISSUE TITLE
radicale2: can't make it run

### ISSUE THREAD

**Issue by wehkah** [openwrt/packages#17225]
I am trying to install radicale2 onto my fb4040, running OpenWrt 21.02.1 but it simply does not start. I am sorry for not being able to provide better error description, but there is none. I repeated the installation several times from scratch, each time removing everything related to this package. I tried manual installation, I tried installation via GUI. There is also no output to any logfile.

After configuration, I call "/etc/init.d/radicale2 start", but nothing happens at all: no running service, no error message.

How can I make the app more verbose? How can I at least produce some logfile output?

This is frustrating. Thanks in advance for any help!

**Comment by jefferyto** [comment]
What do you see when you run `logread` at the command line?

**Comment by wehkah** [comment]
There's a missing dependency, as I found in this thread:

https://github.com/openwrt/packages/issues/11062

> Radicale does not start since the module urllib is missing.

After installing urllig, radicale2 is working now!

**Comment by jefferyto** [comment]
radicale2 [depends](https://github.com/openwrt/packages/blob/032d0157c30bca400d058087e920c8a6b94851e5/net/radicale2/Makefile#L32) on python3, and python3 already depends on python3-urllib. Not sure why it wasn't already installed on your system.

**Comment by wehkah** [comment]
> Not sure why it wasn't already installed on your system.

The reason is more than obvious, just look at the other thread I quoted: the package management is missing a dependency. That has not been changed since OpenWRT 19.07, the version that the user in the other thread is talking about.

**Comment by jefferyto** [comment]
If you actually read the thread you quoted, you would see that the issue was already fixed in master (which 21.02 is based on) and fixed in 19.07 in #11078.

**Comment by wehkah** [comment]
What about the second part of the sentence you quoted?

"...,however, branch 19.07 does not have python3-urllib as a dependecy."

I did not remove the missing package manually, it simply was not installed automatically when I installed radicale2. 

The thread  #11078 is about radicale, while I tried to install radicale2. Is it possible that the maintainer fixed the dependency for radicale, but forget to fix it for radicale2 as well? Just a thought...

**Comment by jefferyto** [comment]
> Is it possible that the maintainers fixed the dependency for radicale, but forgot to fix it for radicale2 as well?

No.

**Comment by wehkah** [comment]
I am sorry to bother you, but I need your help again. Today I installed the available upgrade and now radicale2 once again won't start. :(

Radicale2 is now version 2.1.12-1. Again, there is no kind of reaction when I call

`/etc/init.d/radicale2 start`

No error, no log file, nothing. And of course: no running radicale.

But, when I call

`python3 -m radicale -C /var/etc/radicale2/config `

the server works as expected. Clients and users can connect.

The package python3-urllib is installed, so this can not be the cause of failure this time.

Why does the start script cause the server to fail, while a direct command makes it work?

**Comment by wehkah** [comment]
This time logread tells me this:


```

Sun Jan 16 12:02:53 2022 daemon.err radicale2[7577]: Traceback (most recent call last):
Sun Jan 16 12:02:53 2022 daemon.err radicale2[7577]:   File "/usr/bin/radicale2", line 33, in <module>
Sun Jan 16 12:02:53 2022 daemon.err radicale2[7577]:     sys.exit(load_entry_point('Radicale==2.1.12', 'console_scripts', 'radicale')())
Sun Jan 16 12:02:53 2022 daemon.err radicale2[7577]:   File "/usr/bin/radicale2", line 25, in importlib_load_entry_point
Sun Jan 16 12:02:53 2022 daemon.err radicale2[7577]:     return next(matches).load()
Sun Jan 16 12:02:53 2022 daemon.err radicale2[7577]: StopIteration
Sun Jan 16 12:02:54 2022 daemon.info procd: Instance radicale2::radicale2 s in a crash loop 17 crashes, 1 seconds since last crash

```

**Comment by jefferyto** [comment]
What packages do you have installed (`opkg list-installed`)?

**Comment by wehkah** [comment]
Here you are:

```
apcupsd - 3.14.14-3
at - 3.2.1-1
ath10k-board-qca4019 - 20201118-3
ath10k-firmware-qca4019-ct - 2020-11-08-1
base-files - 1434-r16325-88151b8303
block-mount - 2021-01-04-c53b1882-1
busybox - 1.33.1-6
ca-bundle - 20210119-1
ca-certificates - 20210119-1
cgi-io - 2021-09-08-98cef9dd-20
collectd - 5.12.0-10
coreutils - 8.32-6
coreutils-date - 8.32-6
coreutils-md5sum - 8.32-6
curl - 7.80.0-1
dejavu-fonts-ttf-DejaVuSansMono-Bold - 2.37-1
dnsmasq - 2.85-8
dropbear - 2020.81-2
e2fsprogs - 1.45.6-2
fdisk - 2.36.1-2
firewall - 2021-03-23-61db17ed-1
fritz-caldata - 1
fritz-tffs - 1
fstools - 2021-01-04-c53b1882-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2020-10-25-9ef88681-2
hashdeep - 4.4-1
hostapd-common - 2020-06-08-5a8b3662-35
imagemagick - 7.0.9-2
ip6tables - 1.8.7-1
iptables - 1.8.7-1
iw - 5.9-8fab0c9e-1
iwinfo - 2021-04-30-c45f0b58-2.1
jshn - 2021-05-16-b14c4688-2
jsonfilter - 2018-02-04-c7e938d6-1
kernel - 5.4.154-1-d04d8d4d6f3bad7588be7c9e49004fda
kmod-ath - 5.4.154+5.10.68-1-1
kmod-ath10k-ct - 5.4.154+2021-09-22-e6a7d5b5-1
kmod-cfg80211 - 5.4.154+5.10.68-1-1
kmod-crypto-crc32c - 5.4.154-1
kmod-crypto-hash - 5.4.154-1
kmod-crypto-md5 - 5.4.154-1
kmod-crypto-sha1 - 5.4.154-1
kmod-crypto-sha256 - 5.4.154-1
kmod-crypto-sha512 - 5.4.154-1
kmod-fs-ext4 - 5.4.154-1
kmod-gpio-button-hotplug - 5.4.154-3
kmod-hid - 5.4.154-1
kmod-hid-generic - 5.4.154-1
kmod-hwmon-core - 5.4.154-1
kmod-input-core - 5.4.154-1
kmod-input-evdev - 5.4.154-1
kmod-ip6tables - 5.4.154-1
kmod-ipt-conntrack - 5.4.154-1
kmod-ipt-core - 5.4.154-1
kmod-ipt-nat - 5.4.154-1
kmod-ipt-offload - 5.4.154-1
kmod-leds-gpio - 5.4.154-1
kmod-lib-crc-ccitt - 5.4.154-1
kmod-lib-crc16 - 5.4.154-1
kmod-lib-crc32c - 5.4.154-1
kmod-mac80211 - 5.4.154+5.10.68-1-1
kmod-nf-conntrack - 5.4.154-1
kmod-nf-conntrack6 - 5.4.154-1
kmod-nf-flow - 5.4.154-1
kmod-nf-ipt - 5.4.154-1
kmod-nf-ipt6 - 5.4.154-1
kmod-nf-nat - 5.4.154-1
kmod-nf-reject - 5.4.154-1
kmod-nf-reject6 - 5.4.154-1
kmod-nls-base - 5.4.154-1
kmod-ppp - 5.4.154-1
kmod-pppoe - 5.4.154-1
kmod-pppox - 5.4.154-1
kmod-sched - 5.4.154-1
kmod-sched-core - 5.4.154-1
kmod-scsi-core - 5.4.154-1
kmod-slhc - 5.4.154-1
kmod-usb-core - 5.4.154-1
kmod-usb-dwc3 - 5.4.154-1
kmod-usb-dwc3-qcom - 5.4.154-1
kmod-usb-ehci - 5.4.154-1
kmod-usb-hid - 5.4.154-1
kmod-usb-ohci - 5.4.154-1
kmod-usb-ohci-pci - 5.4.154-1
kmod-usb-serial - 5.4.154-1
kmod-usb-serial-pl2303 - 5.4.154-1
kmod-usb-storage - 5.4.154-1
kmod-usb-storage-uas - 5.4.154-1
kmod-usb-uhci - 5.4.154-1
kmod-usb2 - 5.4.154-1
kmod-usb3 - 5.4.154-1
libblkid1 - 2.36.1-2
libblobmsg-json20210516 - 2021-05-16-b14c4688-2
libbz2-1.0 - 1.0.8-1
libc - 1.1.24-3
libcomerr0 - 1.45.6-2
libcurl4 - 7.80.0-1
libdb47 - 4.7.25.4.NC-6
libelf1 - 0.180-1
libevdev - 1.12.0-1
libext2fs2 - 1.45.6-2
libfdisk1 - 2.36.1-2
libffi - 3.3-2
libfreetype - 2.10.4-1
libgcc1 - 8.4.0-3
libgdbm - 1.18.1-2
libip4tc2 - 1.8.7-1
libip6tc2 - 1.8.7-1
libiwinfo-data - 2021-04-30-c45f0b58-2.1
libiwinfo-lua - 2021-04-30-c45f0b58-2.1
libiwinfo20210430 - 2021-04-30-c45f0b58-2.1
libjpeg-turbo - 2.0.6-1
libjson-c5 - 0.15-2
libjson-script20210516 - 2021-05-16-b14c4688-2
libltdl7 - 2.4.6-2
liblua5.1.5 - 5.1.5-9
liblucihttp-lua - 2021-06-11-3dc89af4-1
liblucihttp0 - 2021-06-11-3dc89af4-1
liblzma - 5.2.5-3
libncurses6 - 6.2-3
libnghttp2-14 - 1.43.0-1
libnl-tiny1 - 2020-08-05-c291088f-2
libopenssl-conf - 1.1.1l-1
libopenssl1.1 - 1.1.1l-1
libpng - 1.6.37-10
libpthread - 1.1.24-3
libpython3-3.9 - 3.9.9-1
libqrencode - 4.1.1-1
libreadline8 - 8.1-1
librt - 1.1.24-3
libsmartcols1 - 2.36.1-2
libsqlite3-0 - 3330000-1
libss2 - 1.45.6-2
libtiff5 - 4.2.0-1
libubox20210516 - 2021-05-16-b14c4688-2
libubus-lua - 2021-06-30-4fc532c8-2
libubus20210630 - 2021-06-30-4fc532c8-2
libuci20130104 - 2020-10-06-52bbc99f-5
libuclient20201210 - 2021-05-14-6a6011df-1
libudev-zero - 1.0.0-1
libusb-1.0-0 - 1.0.24-4
libusb-compat4 - 0.1.7-2
libustream-wolfssl20201210 - 2020-12-10-68d09243-1
libuuid1 - 2.36.1-2
libwolfssl4.8.1.66253b90 - 4.8.1-stable-4
libxtables12 - 1.8.7-1
logd - 2020-10-25-9ef88681-2
lua - 5.1.5-9
luci - git-20.074.84698-ead5e81
luci-app-commands - git-21.099.45423-3fff72a
luci-app-diag-core - git-20.036.57178-625abbf
luci-app-firewall - git-21.312.70727-3eac573
luci-app-opkg - git-21.079.58598-6639e31
luci-app-radicale2 - git-21.285.75837-3a8af31
luci-app-uhttpd - git-20.202.77895-d662f3c
luci-app-wifischedule - git-20.110.55046-74da73b
luci-base - git-21.295.67054-13df80d
luci-compat - git-21.099.45066-7bb2fc4
luci-i18n-base-de - git-21.344.62118-06a2913
luci-i18n-commands-de - git-21.331.26645-deeb842
luci-i18n-diag-core-de - git-21.056.54688-329d9a3
luci-i18n-firewall-de - git-21.344.62118-06a2913
luci-i18n-opkg-de - git-21.365.39273-fc3aa65
luci-i18n-radicale2-de - git-21.352.28797-eaad9d9
luci-i18n-uhttpd-de - git-21.344.62118-06a2913
luci-i18n-wifischedule-de - git-21.365.39273-fc3aa65
luci-lib-base - git-20.232.39649-1f6dc29
luci-lib-ip - git-20.250.76529-62505bd
luci-lib-jsonc - git-19.317.29469-8da8f38
luci-lib-nixio - git-20.234.06894-c4a4e43
luci-mod-admin-full - git-19.253.48496-3f93650
luci-mod-network - git-21.295.67048-4d3de0e
luci-mod-status - git-21.295.66779-853a128
luci-mod-system - git-21.295.66903-8acd0d7
luci-proto-ipv6 - git-21.148.49484-14511e5
luci-proto-ppp - git-21.163.64918-6c6559a
luci-ssl - git-20.244.36115-e10f954
luci-theme-bootstrap - git-21.320.44446-0cee46b
luci-theme-openwrt-2020 - git-21.295.66961-f9e9fcf
mtd - 26
nano - 6.0-1
netifd - 2021-07-26-440eb064-1
odhcp6c - 2021-01-09-53f07e90-16
odhcpd-ipv6only - 2021-07-18-bc9d317f-3
openssl-util - 1.1.1l-1
openwrt-keyring - 2021-02-20-49283916-2
opkg - 2021-06-13-1bf042dd-1
ppp - 2.4.8.git-2020-10-03-3
ppp-mod-pppoe - 2.4.8.git-2020-10-03-3
procd - 2021-02-23-37eed131-1
px5g-wolfssl - 3
python3 - 3.9.9-1
python3-asyncio - 3.9.9-1
python3-base - 3.9.9-1
python3-bcrypt - 3.1.7-4
python3-cffi - 1.14.6-1
python3-cgi - 3.9.9-1
python3-cgitb - 3.9.9-1
python3-codecs - 3.9.9-1
python3-ctypes - 3.9.9-1
python3-dateutil - 2.8.1-3
python3-dbm - 3.9.9-1
python3-decimal - 3.9.9-1
python3-distutils - 3.9.9-1
python3-email - 3.9.9-1
python3-gdbm - 3.9.9-1
python3-light - 3.9.9-1
python3-logging - 3.9.9-1
python3-lzma - 3.9.9-1
python3-multiprocessing - 3.9.9-1
python3-ncurses - 3.9.9-1
python3-openssl - 3.9.9-1
python3-passlib - 1.7.2-2
python3-pkg-resources - 58.1.0-1
python3-ply - 3.11-2
python3-pycparser - 2.20-5
python3-pydoc - 3.9.9-1
python3-readline - 3.9.9-1
python3-setuptools - 58.1.0-1
python3-six - 1.16.0-1
python3-sqlite3 - 3.9.9-1
python3-unittest - 3.9.9-1
python3-urllib - 3.9.9-1
python3-vobject - 0.9.6.1-2
python3-xml - 3.9.9-1
qrencode - 4.1.1-1
radicale2 - 2.1.12-1
rpcd - 2021-03-11-ccb75178-1
rpcd-mod-file - 2021-03-11-ccb75178-1
rpcd-mod-iwinfo - 2021-03-11-ccb75178-1
rpcd-mod-luci - 20210614
rpcd-mod-rad2-enc - 20190109
rpcd-mod-rrdns - 20170710
swconfig - 12
terminfo - 6.2-3
ubi-utils - 2.1.2-1
uboot-envtools - 2021.01-10
ubox - 2020-10-25-9ef88681-2
ubus - 2021-06-30-4fc532c8-2
ubusd - 2021-06-30-4fc532c8-2
uci - 2020-10-06-52bbc99f-5
uclibcxx - 0.2.5-3
uclient-fetch - 2021-05-14-6a6011df-1
uhttpd - 2021-03-21-15346de8-2
uhttpd-mod-ubus - 2021-03-21-15346de8-2
urandom-seed - 3
urngd - 2020-01-21-c7f7b6b6-1
usbids - 0.354-1
usbutils - 013-2
usign - 2020-05-23-f1f65026-1
wifischedule - 1-3
wireless-regdb - 2021.04.21-1
wpad-basic-wolfssl - 2020-06-08-5a8b3662-35
zlib - 1.2.11-3

```

**Comment by jefferyto** [comment]
Can you try removing and reinstalling the radicale2 package?

**Comment by wehkah** [comment]
Been there, done that... That was also my first thought, and I even tried two different ways of deinstalling and reinstalling: via web GUI and via command line. But neither way doesn't make any difference: the start script fails, while starting the service by 

`/usr/bin/python3 -m radicale -C /var/etc/radicale2/config &`

does work. Until I will find the solution to this, I put the above command into /etc/rc.local, so the service is started when the router starts. 

I took a look into /etc/init.d/radicale2 and according to my limited knowledge of scripting, I think that this script creates the config file  `/var/etc/radicale2/config`, using the contents of `/etc/config/radicale2` and then it starts the server. Correct my if I am wrong there!

But if I understood that correctly, the command line should not work either, because it uses the same config file. So I guess there's some deeper magic going on.

**Comment by jefferyto** [comment]
I have installed radicale2 on armvirt-32 (in qemu) and verified that it starts with no issue. The problem isn't the init script, something is wrong with your Python installation.

**Comment by wehkah** [comment]
I removed radicale2 and every python package that was installed. After that, I re-installed radicale2, and it automatically installed these packages:

```
root@fb4040:~# opkg install radicale2
Installing radicale2 (2.1.12-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/radicale2_2.1.12-1_arm_cortex-a7_neon-vfpv4.ipk
Installing libpython3-3.9 (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/libpython3-3.9_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-base (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-base_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing libffi (3.3-2) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/libffi_3.3-2_arm_cortex-a7_neon-vfpv4.ipk
Installing libbz2-1.0 (1.0.8-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/base/libbz2-1.0_1.0.8-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-light (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-light_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-unittest (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-unittest_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-ncurses (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-ncurses_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-ctypes (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-ctypes_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-pydoc (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-pydoc_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-decimal (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-decimal_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-multiprocessing (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-multiprocessing_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-codecs (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-codecs_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing libreadline8 (8.1-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/base/libreadline8_8.1-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-readline (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-readline_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing libgdbm (1.18.1-2) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/libgdbm_1.18.1-2_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-gdbm (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-gdbm_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-email (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-email_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-urllib (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-urllib_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-xml (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-xml_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing libsqlite3-0 (3330000-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/libsqlite3-0_3330000-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-sqlite3 (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-sqlite3_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-logging (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-logging_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-distutils (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-distutils_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-openssl (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-openssl_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-cgi (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-cgi_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-cgitb (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-cgitb_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing libdb47 (4.7.25.4.NC-6) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/libdb47_4.7.25.4.NC-6_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-dbm (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-dbm_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing liblzma (5.2.5-3) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/liblzma_5.2.5-3_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-lzma (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-lzma_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-asyncio (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-asyncio_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3 (3.9.9-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3_3.9.9-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-six (1.16.0-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-six_1.16.0-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-dateutil (2.8.1-3) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-dateutil_2.8.1-3_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-vobject (0.9.6.1-2) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-vobject_0.9.6.1-2_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-pkg-resources (58.1.0-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-pkg-resources_58.1.0-1_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-setuptools (58.1.0-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-setuptools_58.1.0-1_arm_cortex-a7_neon-vfpv4.ipk
Configuring libbz2-1.0.
Configuring libpython3-3.9.
Configuring python3-base.
Configuring libffi.
Configuring python3-light.
Configuring python3-email.
Configuring python3-urllib.
Configuring python3-pydoc.
Configuring liblzma.
Configuring python3-cgi.
Configuring python3-cgitb.
Configuring python3-decimal.
Configuring python3-xml.
Configuring python3-unittest.
Configuring python3-ncurses.
Configuring python3-ctypes.
Configuring python3-multiprocessing.
Configuring python3-codecs.
Configuring libreadline8.
Configuring python3-readline.
Configuring libgdbm.
Configuring python3-gdbm.
Configuring libsqlite3-0.
Configuring python3-sqlite3.
Configuring python3-logging.
Configuring python3-distutils.
Configuring python3-openssl.
Configuring libdb47.
Configuring python3-dbm.
Configuring python3-lzma.
Configuring python3-asyncio.
Configuring python3.
Configuring python3-six.
Configuring python3-dateutil.
Configuring python3-pkg-resources.
Configuring python3-setuptools.
Configuring python3-vobject.
Configuring radicale2.

```
After that, radicale2 still would not start using the starting script. Then I remembered reading something about starting problems when bcrypt was not installed, so I did

```
root@fb4040:~# opkg install python3-bcrypt
Installing python3-bcrypt (3.1.7-4) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-bcrypt_3.1.7-4_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-ply (3.11-2) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-ply_3.11-2_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-pycparser (2.20-5) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-pycparser_2.20-5_arm_cortex-a7_neon-vfpv4.ipk
Installing python3-cffi (1.14.6-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.1/packages/arm_cortex-a7_neon-vfpv4/packages/python3-cffi_1.14.6-1_arm_cortex-a7_neon-vfpv4.ipk
Configuring python3-ply.
Configuring python3-pycparser.
Configuring python3-cffi.
Configuring python3-bcrypt.

```
But still, radicale2 will only start when I use the command line.

**Comment by wehkah** [comment]
Some additional information:

Although the init script fails, it tells me that radicale2 is running:

```
root@fb4040:~# /etc/init.d/radicale2 status
running
```

That statement is not true:

```
root@fb4040:~# ps | grep radical
24415 root      1100 R    grep radical
```

Where does the init script that information? I can not find any pid file for this.
 
If I use the argument "trace" I get this error message:

```
root@fb4040:~# logread
...
Fri Jan 21 08:06:50 2022 daemon.warn procd: Seccomp support for radicale2::radicale2 not available
```

Followed by the same error messages as shown above ("traceback...") about the crash loop. But still, the init script insists that radicale2 is running:

```
root@fb4040:~# /etc/init.d/radicale2 status
running
```
