### ISSUE TITLE
python3-light: cannot import importlib.metadata

### ISSUE THREAD

**Issue by julienmalik** [openwrt/packages#20462]
Maintainer: @jefferyto 
Environment: x86 / 22.03, x86 / master

Description: python3-light installs importlib.metadata package, that can't be imported

```
$ docker run --rm  -it openwrtorg/rootfs:x86-64
[...]
root@container:/# opkg update
root@container:/# opkg install python3-light
root@container:/# ls /usr/lib/python3.10/importlib/metadata/
__init__.pyc      _adapters.pyc     _collections.pyc  _functools.pyc    _itertools.pyc    _meta.pyc         _text.pyc
root@container:/# python3 -c "import importlib.metadata"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 6, in <module>
ModuleNotFoundError: No module named 'email'
```

discovered by : https://github.com/openwrt/packages/issues/20441

It seems it requires at least `python3-email` and `python3-urllib`
```
root@container:/# opkg install python3-email
Installing python3-email (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-email_3.10.7-3_x86_64.ipk
Configuring python3-email.
root@container:/# python3 -c "import importlib.metadata"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 7, in <module>
  File "/usr/lib/python3.10/pathlib.py", line 14, in <module>
ModuleNotFoundError: No module named 'urllib'
root@container:/# opkg install python3-urllib
Installing python3-urllib (3.10.7-3) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/x86_64/packages/python3-urllib_3.10.7-3_x86_64.ipk
Configuring python3-urllib.
root@container:/# python3 -c "import importlib.metadata"
root@container:/# 
```

Also found https://github.com/openwrt/packages/issues/12942 by looking around in the issue tracker

**Comment by jefferyto** [comment]
Thanks for opening this - I've done a quick check of python3-light and there are more references to other separately-packaged modules. I'm going to wait until after branching for 23.05 before trying to address the full issue as I think it may affect many other packages.

**Comment by jefferyto** [comment]
AFAIK circular references continue to exist in Python core packages to this day

**Comment by commodo** [comment]
Coming back around to this.

I've started seeing this issue as well when writing `test.sh` scripts.
Claude would write tests using `importlib` to check for the version, but that would not work.
So, we'd revert to using `__version__` , but even that does not seem to be present in all modules.

Another issue was with the circular dependency of `email` and `urllib` ; that was fixed with PR https://github.com/openwrt/packages/pull/29048

But for `importlib`, and idea would be to split this into it's own module/package.
I guess....  a `test.sh` for Python3 and all it's sub-packages would be an interesting idea as well.

We've not been great at testing these packages, and this `test.sh` mechanism is a life-saver in this regard
