### ISSUE TITLE
Ruby 2.4

### ISSUE THREAD

**Issue by joker5bb** [openwrt/packages#3911]
Ruby 2.4 fails to build 

```
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-gnu-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="-w" --make-flags="w" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
installing binary commands:   /home/user/openwrt-pineapple-tetra/staging_dir/host/bin
installing base libraries:    /home/user/openwrt-pineapple-tetra/staging_dir/host/lib
installing arch files:        /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/2.4.0/x86_64-linux-gnu
installing pkgconfig data:    /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/pkgconfig
installing command scripts:   /home/user/openwrt-pineapple-tetra/staging_dir/host/bin
installing library scripts:   /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/2.4.0
installing common headers:    /home/user/openwrt-pineapple-tetra/staging_dir/host/include/ruby-2.4.0
installing manpages:          /home/user/openwrt-pineapple-tetra/staging_dir/host/share/man/man1
installing extension objects: /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/2.4.0/x86_64-linux-gnu
installing extension objects: /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/site_ruby/2.4.0/x86_64-linux-gnu
installing extension objects: /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/vendor_ruby/2.4.0/x86_64-linux-gnu
installing extension headers: /home/user/openwrt-pineapple-tetra/staging_dir/host/include/ruby-2.4.0/x86_64-linux-gnu
installing extension scripts: /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/2.4.0
installing extension scripts: /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/site_ruby/2.4.0
installing extension scripts: /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/vendor_ruby/2.4.0
installing extension headers: /home/user/openwrt-pineapple-tetra/staging_dir/host/include/ruby-2.4.0/ruby
installing default gems:      /home/user/openwrt-pineapple-tetra/staging_dir/host/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
Invalid gemspec in [/home/user/openwrt-pineapple-tetra/build_dir/host/ruby-2.4.0/ext/psych/psych.gemspec]: cannot load such file -- date
./tool/rbinstall.rb:707:in `block (2 levels) in <main>': invalid spec in /home/user/openwrt-pineapple-tetra/build_dir/host/ruby-2.4.0/ext/psych/psych.gemspec (RuntimeError)
	from ./tool/rbinstall.rb:706:in `map'
	from ./tool/rbinstall.rb:706:in `block in <main>'
	from ./tool/rbinstall.rb:822:in `block in <main>'
	from ./tool/rbinstall.rb:819:in `each'
	from ./tool/rbinstall.rb:819:in `<main>'
uncommon.mk:284: recipe for target 'do-install-nodoc' failed
make[3]: *** [do-install-nodoc] Error 1
make[3]: Leaving directory '/home/user/openwrt-pineapple-tetra/build_dir/host/ruby-2.4.0'
Makefile:1387: recipe for target '/home/user/openwrt-pineapple-tetra/staging_dir/host/stamp/.ruby_installed' failed
make[2]: *** [/home/user/openwrt-pineapple-tetra/staging_dir/host/stamp/.ruby_installed] Error 2
make[2]: Leaving directory '/home/user/openwrt-pineapple-tetra/feeds/packages/lang/ruby'
package/Makefile:191: recipe for target 'package/feeds/packages/ruby/host/compile' failed
make[1]: *** [package/feeds/packages/ruby/host/compile] Error 2
make[1]: Leaving directory '/home/user/openwrt-pineapple-tetra'
/home/user/openwrt-pineapple-tetra/include/toplevel.mk:181: recipe for target 'package/ruby/compile' failed
make: *** [package/ruby/compile] Error 2

```

**Comment by zuav** [comment]
Hi!
I'm building ruby 2.4.1 (on macos, for our project) and have the same error.
Could you please tell me how you fixed that error?
