### ISSUE TITLE
python-cryptography - error compile/build (LEDE-trunk-r3114+)

### ISSUE THREAD

**Issue by build000** [openwrt/packages#3913]
@jefferyto @commodo 
make -j8 BUILD_LOG=1 **(error)**
cat logs/***/compile.txt

```
make[3]: Entering directory '/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/feeds/packages/lang/python-cryptography'
. /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/include/shell.sh; gzip -dc /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/dl/cryptography-1.5.1.tar.gz | tar -C /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.. -xf - 
[ ! -d ./src/ ] || cp -fpR ./src/* /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1
touch /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.prepared_3d01556c4080eccc5ced08698d8295b6_n
rm -f /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/stamp/.python-cryptography_installed
(cd /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/./; if [ -x ./configure ]; then find /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/ -name config.guess | xargs -r chmod u+w; find /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/ -name config.guess | xargs -r -n1 cp --remove-destination /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/scripts/config.guess; find /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/ -name config.sub | xargs -r chmod u+w; find /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/ -name config.sub | xargs -r -n1 cp --remove-destination /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/scripts/config.sub; AR="powerpc-openwrt-linux-musl-gcc-ar" AS="powerpc-openwrt-linux-musl-gcc -c -Os -pipe -mcpu=464fp -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1:cryptography-1.5.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=powerpc-openwrt-linux-musl-ld NM="powerpc-openwrt-linux-musl-gcc-nm" CC="powerpc-openwrt-linux-musl-gcc" GCC="powerpc-openwrt-linux-musl-gcc" CXX="powerpc-openwrt-linux-musl-g++" RANLIB="powerpc-openwrt-linux-musl-gcc-ranlib" STRIP=powerpc-openwrt-linux-musl-strip OBJCOPY=powerpc-openwrt-linux-musl-objcopy OBJDUMP=powerpc-openwrt-linux-musl-objdump SIZE=powerpc-openwrt-linux-musl-size CFLAGS="-Os -pipe -mcpu=464fp -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1:cryptography-1.5.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mcpu=464fp -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1:cryptography-1.5.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/include -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/include -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/usr/include -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/include/fortify -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/include " LDFLAGS="-L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/lib -L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/lib -L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/usr/lib -L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/lib -znow -zrelro "   ./configure --target=powerpc-openwrt-linux --host=powerpc-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   _python_sysroot="/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16" _python_prefix="/usr" _python_exec_prefix="/usr" ; fi; )
rm -f /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.configured_*
touch /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.configured_yyyyyyy
install -d -m0755 /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/ipkg-install//usr/lib/python2.7/site-packages
if [ "" == "HOST" ]; then export PYTHONPATH="/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/hostpkg/lib/python2.7:/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/hostpkg/lib/python2.7/site-packages"; export PYTHONDONTWRITEBYTECODE=0; else export PYTHONPATH="/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/lib/python2.7:/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16//usr/lib/python2.7/site-packages:/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/ipkg-install//usr/lib/python2.7/site-packages"; export PYTHONDONTWRITEBYTECODE=1; export _python_sysroot="/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16"; export _python_prefix="/usr"; export _python_exec_prefix="/usr"; fi; export PYTHONOPTIMIZE="";   cd /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/; CC="powerpc-openwrt-linux-musl-gcc" CCSHARED="powerpc-openwrt-linux-musl-gcc -fPIC" CXX="powerpc-openwrt-linux-musl-g++" LD="powerpc-openwrt-linux-musl-gcc" LDSHARED="powerpc-openwrt-linux-musl-gcc -shared" CFLAGS="-Os -pipe -mcpu=464fp -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1:cryptography-1.5.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CPPFLAGS="-I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/include -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/include -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/usr/include -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/include/fortify -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/include -I/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/include/python2.7" LDFLAGS="-L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/lib -L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/lib -L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/usr/lib -L/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/toolchain-powerpc_464fp_gcc-5.4.0_musl-1.1.16/lib -znow -zrelro -lpython2.7" _PYTHON_HOST_PLATFORM=linux2 __PYVENV_LAUNCHER__="/usr/bin/python2.7"    /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/hostpkg/bin/python2.7   ./setup.py install --prefix="/usr" --root="/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/ipkg-install" ;
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

warning: easy_install: byte-compiling is disabled, skipping.


Installed /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs/cffi-1.9.1-py2.7-linux2.egg
Searching for pycparser
Reading https://pypi.python.org/simple/pycparser/
Downloading https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz#md5=ca98dcb50bc1276f230118f6af5a40c7
Best match: pycparser 2.17
Processing pycparser-2.17.tar.gz
Writing /tmp/easy_install-Qqss8n/pycparser-2.17/setup.cfg
Running pycparser-2.17/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Qqss8n/pycparser-2.17/egg-dist-tmp-Y4UMlU
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

zip_safe flag not set; analyzing archive contents...
Moving pycparser-2.17-py2.7.egg to /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs

Installed /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs/pycparser-2.17-py2.7.egg
Traceback (most recent call last):
  File "./setup.py", line 334, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/lib/python2.7/site-packages/setuptools/dist.py", line 318, in __init__
    _Distribution.__init__(self, attrs)
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/staging_dir/target-powerpc_464fp_musl-1.1.16/usr/lib/python2.7/site-packages/setuptools/dist.py", line 376, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs/cffi-1.9.1-py2.7-linux2.egg/cffi/setuptools_ext.py", line 187, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs/cffi-1.9.1-py2.7-linux2.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs/cffi-1.9.1-py2.7-linux2.egg/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "src/_cffi_src/build_openssl.py", line 81, in <module>
    extra_link_args=extra_link_args(compiler_type()),
  File "./src/_cffi_src/utils.py", line 61, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "./src/_cffi_src/utils.py", line 69, in build_ffi
    ffi = FFI()
  File "/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs/cffi-1.9.1-py2.7-linux2.egg/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: /home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.eggs/cffi-1.9.1-py2.7-linux2.egg/_cffi_backend.so: wrong ELF class: ELFCLASS32
Makefile:53: recipe for target '/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.built' failed
make[3]: *** [/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/build_dir/target-powerpc_464fp_musl-1.1.16/cryptography-1.5.1/.built] Error 1
make[3]: Leaving directory '/home/dom/Pulpit/Projekty/WNDR4700-LEDE-trunk/feeds/packages/lang/python-cryptography'
```
It seems to me that this is the consequence of the resignation of python(3)-pip, etc. as separate packages... ;)

**Comment by commodo** [comment]
my bad ; will fix
likely related to removal of python(3)-pip ;
those packages did not get removed, they got merged into python(3) ; some host-side deps may need fixing

i'll try to get fixing this next week;
i'm actually trying to merge/compress some python packages
something similar to https://github.com/openwrt/packages/tree/master/lang/python-packages

i think that some python packages exist [in the feeds] simply to serve the dependency of more complex package ; and i think this can be addressed somehow in a better way
