### ISSUE TITLE
python-pyopenssl: error on import OpenSSL in python

### ISSUE THREAD

**Issue by valdi74** [openwrt/packages#4499]
Maintainer: Jeffery To <jeffery.to@gmail.com>
Environment: (x86/64, VM, LEDE snapshot Tue Jun 20 02:25:19 2017)

Description:

There is an error 'No module named _openssl' when trying to import module OpenSSL in python:

```
root@LEDE:~# python
Python 2.7.13 (default, Jun 20 2017, 08:11:00)
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
ImportError: No module named _openssl
```
Enviroment: fresh LEDE install (snapshot Tue Jun 20 02:25:19 2017) on x86/64 arch.

Packages installed:
```
root@LEDE:~# opkg install python-pyopenssl
Installing python-pyopenssl (16.1.0-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-pyopenssl_16.1.0-1_x86_64.ipk
Installing zlib (1.2.11-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/base/zlib_1.2.11-1_x86_64.ipk
Installing python-base (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-base_2.7.13-5_x86_64.ipk
Installing libffi (3.2.1-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/libffi_3.2.1-2_x86_64.ipk
Installing libbz2 (1.0.6-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/base/libbz2_1.0.6-2_x86_64.ipk
Installing python-light (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-light_2.7.13-5_x86_64.ipk
Installing libopenssl (1.0.2k-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/base/libopenssl_1.0.2k-1_x86_64.ipk
Installing python-ctypes (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-ctypes_2.7.13-5_x86_64.ipk
Installing python-pydoc (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-pydoc_2.7.13-5_x86_64.ipk
Installing python-multiprocessing (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-multiprocessing_2.7.13-5_x86_64.ipk
Installing python-logging (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-logging_2.7.13-5_x86_64.ipk
Installing python-codecs (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-codecs_2.7.13-5_x86_64.ipk
Installing libsqlite3 (3190200-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/libsqlite3_3190200-1_x86_64.ipk
Installing python-sqlite3 (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-sqlite3_2.7.13-5_x86_64.ipk
Installing libgdbm (1.11-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/libgdbm_1.11-1_x86_64.ipk
Installing python-gdbm (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-gdbm_2.7.13-5_x86_64.ipk
Installing python-email (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-email_2.7.13-5_x86_64.ipk
Installing python-distutils (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-distutils_2.7.13-5_x86_64.ipk
Installing python-openssl (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-openssl_2.7.13-5_x86_64.ipk
Installing libexpat (2.2.0-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/libexpat_2.2.0-1_x86_64.ipk
Installing python-xml (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-xml_2.7.13-5_x86_64.ipk
Installing python-compiler (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-compiler_2.7.13-5_x86_64.ipk
Installing libxml2 (2.9.4-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/libxml2_2.9.4-1_x86_64.ipk
Installing libdb47 (4.7.25.4.NC-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/libdb47_4.7.25.4.NC-5_x86_64.ipk
Installing python-db (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-db_2.7.13-5_x86_64.ipk
Installing python-decimal (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-decimal_2.7.13-5_x86_64.ipk
Installing python-unittest (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-unittest_2.7.13-5_x86_64.ipk
Installing terminfo (6.0-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/base/terminfo_6.0-1_x86_64.ipk
Installing libncurses (6.0-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/base/libncurses_6.0-1_x86_64.ipk
Installing python-ncurses (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-ncurses_2.7.13-5_x86_64.ipk
Installing python (2.7.13-5) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python_2.7.13-5_x86_64.ipk
Installing python-ply (3.9-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-ply_3.9-2_x86_64.ipk
Installing python-pycparser (2.14-4) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-pycparser_2.14-4_x86_64.ipk
Installing python-cffi (1.8.3-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-cffi_1.8.3-2_x86_64.ipk
Installing python-enum34 (1.1.6-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-enum34_1.1.6-2_x86_64.ipk
Installing python-idna (2.1-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-idna_2.1-1_x86_64.ipk
Installing python-ipaddress (1.0.17-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-ipaddress_1.0.17-1_x86_64.ipk
Installing python-pyasn1 (0.1.9-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-pyasn1_0.1.9-1_x86_64.ipk
Installing python-six (1.10.0-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-six_1.10.0-2_x86_64.ipk
Installing python-setuptools (28.8.0) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-setuptools_28.8.0_x86_64.ipk
Installing python-cryptography (1.5.1-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/x86_64/packages/python-cryptography_1.5.1-2_x86_64.ipk
Configuring terminfo.
Configuring zlib.
Configuring python-base.
Configuring libffi.
Configuring libbz2.
Configuring python-light.
Configuring python-idna.
Configuring python-codecs.
Configuring libxml2.
Configuring libdb47.
Configuring python-db.
Configuring python-ply.
Configuring python-decimal.
Configuring python-six.
Configuring python-pyasn1.
Configuring python-distutils.
Configuring python-pydoc.
Configuring python-ctypes.
Configuring python-multiprocessing.
Configuring python-logging.
Configuring libsqlite3.
Configuring python-sqlite3.
Configuring libgdbm.
Configuring python-gdbm.
Configuring python-email.
Configuring libopenssl.
Configuring python-openssl.
Configuring libexpat.
Configuring python-xml.
Configuring python-compiler.
Configuring python-unittest.
Configuring libncurses.
Configuring python-ncurses.
Configuring python.
Configuring python-pycparser.
Configuring python-cffi.
Configuring python-setuptools.
Configuring python-enum34.
Configuring python-ipaddress.
Configuring python-cryptography.
Configuring python-pyopenssl.
```

On LEDE 17.01.2 import OpenSSL works fine.

**Comment by commodo** [comment]
could be my fault here 
will check it out
