### ISSUE TITLE
youtube-dl: compiling fails

### ISSUE THREAD

**Issue by Hallo32** [openwrt/packages#5991]
# Issue template (remove lines from top till here)

Maintainer: @ianchi
Environment: Mips, Archer C5/C7, master openwrt

This problem may be related to: https://github.com/openwrt/packages/issues/3778  @commodo 

Config: [config.txt](https://github.com/openwrt/packages/files/1962045/config.txt)

The build fails with the following error message:

```Traceback (most recent call last):
  File "devscripts/make_supportedsites.py", line 13, in <module>
    import youtube_dl
  File "devscripts/../youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "devscripts/../youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "devscripts/../youtube_dl/downloader/__init__.py", line 3, in <module>
    from .common import FileDownloader
  File "devscripts/../youtube_dl/downloader/common.py", line 10, in <module>
    from ..utils import (
  File "devscripts/../youtube_dl/utils.py", line 29, in <module>
    import ssl
  File "/opt/openwrt/master/staging_dir/hostpkg/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
Makefile:82: recipe for target 'supportedsites' failed
make[3]: *** [supportedsites] Error 1
make[3]: Leaving directory '/opt/openwrt/master/build_dir/target-mips_24kc_musl/youtube-dl'
Makefile:53: recipe for target '/opt/openwrt/master/build_dir/target-mips_24kc_musl/youtube-dl/.built' failed
make[2]: *** [/opt/openwrt/master/build_dir/target-mips_24kc_musl/youtube-dl/.built] Error 2
make[2]: Leaving directory '/opt/openwrt/master/feeds/packages/multimedia/youtube-dl'
package/Makefile:107: recipe for target 'package/feeds/packages/youtube-dl/compile' failed
make[1]: *** [package/feeds/packages/youtube-dl/compile] Error 2```

**Comment by BKPepe** [comment]
Hello,

For about a month, I'm updating youtube-dl in OpenWRT and as well in Turris OS.
Would you please tell me, if your issue with the latest version of youtube-dl together with OpenWRT 18.06.01/master still persist? If not, can you please close this issue? :-)

**Comment by diizzyy** [comment]
@hnyman @thess 
Close due to submitter timeout
